Get Parity/OE tests back

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -28,43 +28,43 @@ common: &common
           - ~/.py-geth
         key: cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
 
-# parity_steps: &parity_steps
-  # working_directory: ~/repo
-  # steps:
-    # - checkout
-    # - restore_cache:
-        # keys:
-          # - cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
-    # - run:
-        # name: install dependencies
-        # command: pip install --user tox
-    # - run:
-        # name: install parity if needed
-        # command: |
-          # pip install --user requests eth_utils tqdm eth-hash[pycryptodome]
-          # echo "Job specifies Parity version $PARITY_VERSION"
-          # python tests/integration/parity/install_parity.py $PARITY_VERSION
-    # - run:
-        # name: update parity deps from testing repo if needed
-        # command: |
-          # [ "`cat /etc/*release | grep jessie`" != "" ] && echo "On Jessie - installing missing deps..." || echo "Not on Jessie - doing nothing."
-          # [ "`cat /etc/*release | grep jessie`" != "" ] || exit 0
-          # echo "deb http://ftp.debian.org/debian testing main" > testing.list && sudo mv testing.list /etc/apt/sources.list.d/
-          # sudo apt update
-          # sudo apt-get -t testing install libstdc++6
-    # - run:
-        # name: run tox
-        # command: ~/.local/bin/tox -r
-    # - save_cache:
-        # paths:
-          # - .tox
-          # - ~/.cache/pip
-          # - ~/.local
-          # - ./eggs
-          # - ~/.ethash
-          # - ~/.py-geth
-          # - ~/.parity-bin
-        # key: cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
+parity_steps: &parity_steps
+  working_directory: ~/repo
+  steps:
+    - checkout
+    - restore_cache:
+        keys:
+          - cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
+    - run:
+        name: install dependencies
+        command: pip install --user tox
+    - run:
+        name: install parity if needed
+        command: |
+          pip install --user requests eth_utils tqdm eth-hash[pycryptodome]
+          echo "Job specifies Parity version $PARITY_VERSION"
+          python tests/integration/parity/install_parity.py $PARITY_VERSION
+    - run:
+        name: update parity deps from testing repo if needed
+        command: |
+          [ "`cat /etc/*release | grep jessie`" != "" ] && echo "On Jessie - installing missing deps..." || echo "Not on Jessie - doing nothing."
+          [ "`cat /etc/*release | grep jessie`" != "" ] || exit 0
+          echo "deb http://ftp.debian.org/debian testing main" > testing.list && sudo mv testing.list /etc/apt/sources.list.d/
+          sudo apt update
+          sudo apt-get -t testing install libstdc++6
+    - run:
+        name: run tox
+        command: ~/.local/bin/tox -r
+    - save_cache:
+        paths:
+          - .tox
+          - ~/.cache/pip
+          - ~/.local
+          - ./eggs
+          - ~/.ethash
+          - ~/.py-geth
+          - ~/.parity-bin
+        key: cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
 
 geth_steps: &geth_steps
   working_directory: ~/repo
@@ -237,14 +237,14 @@ jobs:
       TOXENV: py36-integration-goethereum-ws
       GETH_VERSION: v1.10.1
 
-  # py36-integration-parity-ipc:
-    # <<: *parity_steps
-    # docker:
-      # - image: circleci/python:3.6-stretch
-    # environment:
-      # TOXENV: py36-integration-parity-ipc
-      # PARITY_VERSION: v2.3.5
-      # PARITY_OS: linux
+  py36-integration-parity-ipc:
+    <<: *parity_steps
+    docker:
+      - image: circleci/python:3.6-stretch
+    environment:
+      TOXENV: py36-integration-parity-ipc
+      PARITY_VERSION: v3.2.3
+      PARITY_OS: linux
 
   # py36-integration-parity-http:
     # <<: *parity_steps
@@ -483,7 +483,7 @@ workflows:
       - py36-integration-goethereum-ipc
       - py36-integration-goethereum-http
       - py36-integration-goethereum-ws
-      # - py36-integration-parity-ipc
+      - py36-integration-parity-ipc
       # - py36-integration-parity-http
       # - py36-integration-parity-ws
       - py36-integration-ethtester-pyevm
